apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - port: 3000                # Cổng của service
      targetPort: 3000           # Cổng container (ứng dụng bên trong)
      nodePort: 31100            # Cổng NodePort bên ngoài
      protocol: TCP