apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-publisher
spec:
  replicas: {{ .Values.publisher.replicas }}
  selector:
    matchLabels:
      app: nodejs-publisher
  template:
    metadata:
      labels:
        app: nodejs-publisher
    spec:
      containers:
      - name: nodejs-publisher
        image: {{ .Values.publisher.image }}
        env:
          - name: MQTT_BROKER_URL
            value: {{ .Values.env.MQTT_BROKER_URL | quote }}
          - name: MQTT_CHANNEL
            value: {{ .Values.env.MQTT_CHANNEL | quote }}
        ports:
        - containerPort: 3001
