apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-publisher
spec:
  replicas: {{ .Values.publisher.replicas }}
  selector:
    matchLabels:
      app: nodejs-publisher
  template:
    metadata:
      labels:
        app: nodejs-publisher
    spec:
      containers:
      - name: nodejs-publisher
        image: {{ .Values.publisher.image }}
        ports:
        - containerPort: 3001
