apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-subscriber
spec:
  replicas: {{ .Values.subscriber.replicas }}
  selector:
    matchLabels:
      app: nodejs-subscriber
  template:
    metadata:
      labels:
        app: nodejs-subscriber
    spec:
      containers:
      - name: nodejs-subscriber
        image: {{ .Values.subscriber.image }}
        env:
          - name: MQTT_BROKER_URL
            value: {{ .Values.env.MQTT_BROKER_URL | quote }}
          - name: MQTT_CHANNEL
            value: {{ .Values.env.MQTT_CHANNEL | quote }}
        ports:
        - containerPort: 3000
