apiVersion: v1
kind: Service
metadata:
  name: node-red-service
  labels:
    app: node-red
spec:
  type: NodePort
  ports:
    - port: 1880     
      targetPort: 1880 
      nodePort: 31880
  selector:
    io.kompose.service: nodered