apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: influxdb
  name: influxdb
  namespace: main-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: influxdb
    spec:
      containers:
        - env:
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              value: mytokenmytokenmytoken
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: simulators
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: setup
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: simulators-project
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              value: {{ .Values.influxdb.admin_password }}
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              value: {{ .Values.influxdb.admin_username }}
          image: influxdb:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://influxdb:8086
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 3
          name: influxdb
          ports:
            - containerPort: 8086
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: influxdb
  name: influxdb
  namespace: main-app
spec:
  ports:
    - name: "8086"
      port: 8086
      targetPort: 8086
  selector:
    io.kompose.service: influxdb