apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nodered
  name: nodered
  namespace: main-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodered
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: nodered
    spec:
      containers:
        - env:
            - name: TZ
              value: Africa/Casablanca
          image: namnnh/nodered_custom
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://nodered:1880
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 3
          name: nodered
          ports:
            - containerPort: 1880
              protocol: TCP
          volumeMounts:
            - name: nodered-config-volume
              mountPath: /data/flows.json
              subPath: flows.json
      volumes:
        - name: nodered-config-volume
          configMap:
            name: nodered-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nodered
  name: nodered
  namespace: main-app
spec:
  ports:
    - name: "1880"
      port: 1880
      targetPort: 1880
  selector:
    io.kompose.service: nodered

